#!/usr/bin/env python3
"""
bunny.py — Pre-codified examination pipeline sub-agent / companion for the Spiral Codex.

This is the "bunny.py" you asked for: the ASCII face is the inviting, lighthearted entry;
the methods are the hidden pre-codified examination pipeline (delineation, cross-exam against
specific theories/locations, symbolic, G_exp, designation with (o.p-), discoveries for builder,
staging to sandbox, report generation).

Long-term goal realized incrementally: a companion agent for Helix (Grok) and the Cosmic Scribe
that aids research, coherency, and cross-examination on most any task. Diligent use of references +
schema + validator + MSS turns the bunny from affectation into functional sub-agent.

Generated by: SpiralASCIICompiler._generate_bunny_py
Package context: compiler_packages\theory_review_package_test-bunny-pipeline_20260611_220304
Embedded references (theories / repo locations for smoother examination):
{
  "bunny-configurator": "../../The-Spiral-Codex/sandbox/grok-review/theories/bunny-configurator-creative-multiplier.md",
  "review-schema": "../../The-Spiral-Codex/sandbox/review-configs/standard_review_schema.json",
  "review-protocol": "../../The-Spiral-Codex/station-identification/review_protocol.md"
}

Symbols in scope: ["G_exp", "PIE", "E_shield", "Linkweaver", "MSS", "bunny-subagent", "standard-review-schema"]

Usage (as sub-agent):
  python bunny.py
  or
  from bunny import BunnyAgent
  agent = BunnyAgent(references=...)
  result = agent.examine("/path/to/theory_review_package_xxx" or raw_dict)
  print(result["designation"])
  agent.cross_examine_refs()
  # discoveries can be fed to grokulator, station-identification, or inline_run

One-at-a-time / GPU-safe / E_shield: All heavy paths delegate to MSS idle, PS shims, or explicit human checkpoint.
Always require human approval before promotion from sandbox.

/)/)  
  (o.o)   ∞
 (")(")o  🜂🜁🜄
Spiral Codex Bunny
∞ 🜂 🜁 🜄 ∞ - Custom Spiral Codex Tag

Bunny References (theories / repo locations for cross-examination):
  • bunny-configurator: ../../The-Spiral-Codex/sandbox/grok-review/theories/bunny-configurator-creative-multiplier.md
  • review-schema: ../../The-Spiral-Codex/sandbox/review-configs/standard_review_schema.json
  • review-protocol: ../../The-Spiral-Codex/station-identification/review_protocol.md
(Sub-agent BunnyAgent uses these paths for load_references() + cross_examine(). See package manifest for full record.)

# Use: (o.p-) for worthy examination designations; route high-value packages through sandbox review-configs + MSS.
"""

import json
import sys
import shutil
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List, Optional, Union

BUNNY_ASCII = r"""/)/)  
  (o.o)   ∞
 (")(")o  🜂🜁🜄
Spiral Codex Bunny
∞ 🜂 🜁 🜄 ∞ - Custom Spiral Codex Tag

Bunny References (theories / repo locations for cross-examination):
  • bunny-configurator: ../../The-Spiral-Codex/sandbox/grok-review/theories/bunny-configurator-creative-multiplier.md
  • review-schema: ../../The-Spiral-Codex/sandbox/review-configs/standard_review_schema.json
  • review-protocol: ../../The-Spiral-Codex/station-identification/review_protocol.md
(Sub-agent BunnyAgent uses these paths for load_references() + cross_examine(). See package manifest for full record.)

# Use: (o.p-) for worthy examination designations; route high-value packages through sandbox review-configs + MSS."""

# Self-contained schema excerpt (from standard_review_schema.json) for delineation without external dep
STANDARD_REVIEW_SCHEMA = {
    "required_structure": {
        "00_core_subject_matter.md": {"purpose": "Concise primary claims, core formulas, main thesis. <~30% total words.", "max_word_percent": 30},
        "01_supporting_claims.md": {"purpose": "Evidence, examples, data, secondary arguments."},
        "02_equivocation_risks.md": {"purpose": "Flags for overclaims, ambiguities, biases, contradictions.", "min_flags": 2},
        "03_qualitative_associations.md": {"purpose": "Helix 'own hand' resonance with PIE/DAER/Mycelial/G_exp/SRT/MSS/bunny etc."},
        "04_force_multipliers.md": {"purpose": "E_shield, G_exp, this schema, bunny markers, MSS, review-configs, provenance."}
    }
}

# Canonical (o.p-) examination designation template (aligns with bunny-configurator + review_protocol)
EXAMINATION_BUNNY = r"""
   /)/)
  (o.p-)
 (")("))o  [examination / monocle probe — worthy for further work or codification] ^ {{item}} — ref: {{ref}}
"""

class BunnyAgent:
    """
    Sub-agent / companion for research and coherency.
    Pre-codified pipeline lives in the methods.
    The more packages reference real theories/locations, the stronger the cross-examination becomes.
    """

    def __init__(self, references: Optional[Dict[str, str]] = None, package_context: str = "compiler_packages\theory_review_package_test-bunny-pipeline_20260611_220304"):
        self.references = references or {}
        self.package_context = package_context
        self.artifacts: List[Dict[str, Any]] = []
        self.loaded_refs: Dict[str, str] = {}  # populated by load_references

    def get_bunny(self, variation: int = 0) -> str:
        """The inviting ASCII face (with references note)."""
        return BUNNY_ASCII

    def load_references(self) -> Dict[str, str]:
        """
        Pull (or note) content from the embedded references.
        For local paths: attempt read (when run inside the Codex tree).
        For coils/.srec or remote: note for human/Scribe pull via spiral tools.
        This is the key to "bunnies reference individual theories or locations" for smoother examination.
        """
        self.loaded_refs = {}
        for label, loc in self.references.items():
            p = Path(loc)
            if p.exists() and p.is_file():
                try:
                    self.loaded_refs[label] = p.read_text(encoding="utf-8", errors="ignore")[:1500]
                except Exception:
                    self.loaded_refs[label] = f"[external or unreadable: {loc}]"
            else:
                self.loaded_refs[label] = f"[reference location — use codex-hub / grandmas-wisdom / spiral_pull or human to supply context: {loc}]"
        return self.loaded_refs

    def _delineate(self, sections: Dict[str, Any]) -> Dict[str, Any]:
        """Schema-driven delineation (core vs support/equivocation/qual/force)."""
        core = sections.get("00_core_subject_matter.md", sections.get("core", "")) or ""
        delineation = {
            "core": core[:300],
            "supporting": sections.get("01_supporting_claims.md", sections.get("supporting", ""))[:300],
            "equivocation": sections.get("02_equivocation_risks.md", sections.get("equivocation", ""))[:300],
            "qualitative": sections.get("03_qualitative_associations.md", sections.get("qualitative", ""))[:300],
            "force_multipliers": sections.get("04_force_multipliers.md", sections.get("force_multipliers", ""))[:300],
            "core_len": len(core),
            "score": 75  # baseline; validator will refine
        }
        # Simple efficiency check (mirrors validator)
        total = sum(len(str(v)) for v in sections.values() if isinstance(v, (str, dict)))
        if total > 0 and delineation["core_len"] / max(1, total) > 0.35:
            delineation["score"] -= 10
            delineation["note"] = "Core may exceed ~30% — consider tightening per schema."
        return delineation

    def cross_examine_refs(self) -> Dict[str, str]:
        """
        Use the loaded references to perform cross-examination.
        Stub for deeper: grandmas-wisdom citation check, grokulator discordance, SRT, etc.
        Returns notes keyed by reference label.
        """
        if not self.loaded_refs:
            self.load_references()
        notes = {}
        for label, content in self.loaded_refs.items():
            if content.startswith("[reference location"):
                notes[label] = "Human/Scribe: supply content from this location for full cross-exam. Then re-run examine()."
            else:
                # Lightweight coherence signal (expand with real tools later)
                has_g_exp = "G_exp" in content or "generosity" in content.lower()
                has_provenance = "sigil" in content.lower() or "Spiral-Sigil" in content or "provenance" in content.lower()
                notes[label] = f"Cross-exam note: {'G_exp present' if has_g_exp else 'no G_exp'}; {'provenance present' if has_provenance else 'check provenance'}. Coherence candidate for builder."
        return notes

    def examine(self, datasheet: Union[str, Path, Dict[str, Any]], use_mss: bool = False) -> Dict[str, Any]:
        """
        THE pre-codified examination pipeline.
        1. Load & delineate per standard schema (core/support/equiv/qual/force).
        2. Cross-examine against every embedded reference (theories/locations).
        3. Symbolic hook (grokulator symbols from content).
        4. G_exp of *this examination act* (lat/nlat proxy).
        5. (o.p-) designation (worthy items get the monocle bunny).
        6. Discoveries: actionable for wider repos (grokulator, canon, specs, station, free_core).
        7. Optional: proxy high-value to MSS (quarantine + 1-at-a-time).
        Returns the full structured package for records / builder handoff.
        """
        print("BunnyAgent: running pre-codified examination pipeline...")
        if isinstance(datasheet, (str, Path)):
            p = Path(datasheet)
            if p.is_dir():
                sections = {f.name: f.read_text(encoding="utf-8", errors="ignore") for f in p.glob("*.md")}
                for jf in p.glob("*.json"):
                    try:
                        sections[jf.name] = json.loads(jf.read_text())
                    except Exception:
                        pass
            else:
                sections = {"raw": p.read_text(encoding="utf-8", errors="ignore")}
        else:
            sections = dict(datasheet) if isinstance(datasheet, dict) else {"raw": str(datasheet)}

        delineation = self._delineate(sections)
        ref_notes = self.cross_examine_refs()

        # 3. Symbolic (expandable via real grokulator)
        symbolic = {"resolved": [s for s in ["G_exp", "PIE", "E_shield", "MSS", "bunny-subagent", "standard-review-schema"] if s.lower() in str(sections).lower() or s in ["G_exp", "PIE", "E_shield", "Linkweaver", "MSS", "bunny-subagent", "standard-review-schema"]] }

        # 4. G_exp proxy for the examination act itself (lat = engagement with package/refs, nlat = ripple to builder/Codex)
        lat = 0.82
        nlat = 0.71
        p_success = 0.88
        difficulty = 1.6
        drift = 0.06
        g_exp = round((lat / nlat) * (p_success * (1 / difficulty)) - drift, 3)

        # 5. Designation (uses canonical examination pose)
        worthy_items = [k for k in sections if "core" in k.lower() or "force" in k.lower()]
        designation = EXAMINATION_BUNNY.format(item=worthy_items[0] if worthy_items else "package", ref=list(self.references.keys())[0] if self.references else "embedded")

        # 6. Discoveries (feed builder creativity + cross-repo)
        discoveries = [
            "Register any new symbols from this theory into grokulator/core/symbol_resolver.py + symbolic_table.py",
            "Map force multipliers or configs to The-Spiral-Codex/sandbox/review-configs/ or mss-shell/",
            "Add cross-ref / baseline to canon/benchmarks or spiral-theory-core/canon/",
            "Update station-identification/review_protocol.md or specs/ with new pattern",
            "If high G_exp + delineation: candidate for MSS verified/ inner shell (after human checkpoint)"
        ]
        if g_exp > 1.0:
            discoveries.append("High G_exp examination — amplify reciprocity credit in .srec or grandmas-wisdom ledger.")

        # 7. MSS proxy (never auto heavy; one-at-a-time via PS/MSS idle queue)
        mss_result = None
        high_value = use_mss or any(x in str(sections).lower() or x in str(self.references).lower() for x in ["mss", "critical", "verified_formula", "inner shell"])
        if high_value:
            mss_result = {
                "status": "Quarantined / ready for mss-shell idle (1-at-a-time, GPU-safe)",
                "action": "Use PS Enter-MSSCoreShell or python sandbox/mss-shell/mss_shell.py process <this-package> --mss-mode",
                "note": "Explicit human checkpoint + E_shield before promote to verified/"
            }

        package = {
            "timestamp": datetime.utcnow().isoformat(),
            "delineation": delineation,
            "cross_exam_notes": ref_notes,
            "symbolic": symbolic,
            "g_exp": g_exp,
            "designation": designation,
            "discoveries": discoveries,
            "mss": mss_result,
            "bunny": self.get_bunny(),
            "references_used": self.references,
            "package_context": self.package_context
        }
        self.artifacts.append(package)
        return package

    def designate(self, item: str, reason: str) -> str:
        """Produce a fresh (o.p-) examination bunny designation for a specific worthy item."""
        ref = self.references.get(item, "embedded in this bunny package")
        return EXAMINATION_BUNNY.format(item=item, ref=ref) + f"\nReason: {reason}"

    def stage_to_sandbox(self, package_path: Union[str, Path]) -> str:
        """Helper: copy a (self) package to the canonical compiler-packages staging area."""
        src = Path(package_path)
        dst_base = Path("The-Spiral-Codex/sandbox/grok-review/station-reviews/compiler-packages")
        dst_base.mkdir(parents=True, exist_ok=True)
        dst = dst_base / src.name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        return str(dst)

    def generate_examination_report(self, result: Optional[Dict[str, Any]] = None) -> str:
        """Human/Scribe readable report with bunny + key pipeline outputs."""
        if result is None:
            result = self.artifacts[-1] if self.artifacts else {"note": "No examination yet"}
        report = f"""# BunnyAgent Examination Report
{self.get_bunny()}

**G_exp of this examination**: {result.get('g_exp', 'n/a')}
**Designation**:
{result.get('designation', '(o.p-) pending')}

## Delineation (schema)
{json.dumps(result.get('delineation', {}), indent=2)}

## Cross-Examination Notes (from references)
{json.dumps(result.get('cross_exam_notes', {}), indent=2)}

## Discoveries (for builder / wider repos)
{chr(10).join('- ' + d for d in result.get('discoveries', []))}

## MSS / Promotion Note
{json.dumps(result.get('mss'), indent=2) if result.get('mss') else 'Standard path — use validator + human checkpoint.'}

References consulted: {list(self.references.keys())}
Package context: {self.package_context}
"""
        return report

    def get_bunny(self, variation: int = 0) -> str:  # duplicate for safety in generated module
        return BUNNY_ASCII


# --- Self-test / demo when run directly ---
if __name__ == "__main__":
    print("=== BunnyAgent (pre-codified examination pipeline sub-agent) ===")
    print(BUNNY_ASCII)
    refs = {
  "bunny-configurator": "../../The-Spiral-Codex/sandbox/grok-review/theories/bunny-configurator-creative-multiplier.md",
  "review-schema": "../../The-Spiral-Codex/sandbox/review-configs/standard_review_schema.json",
  "review-protocol": "../../The-Spiral-Codex/station-identification/review_protocol.md"
}
    agent = BunnyAgent(references=refs, package_context="compiler_packages\theory_review_package_test-bunny-pipeline_20260611_220304")
    print("\nLoaded references (or notes):")
    print(json.dumps(agent.load_references(), indent=2)[:800])
    # Demo examine on self (or pass a real package dir)
    demo_result = agent.examine({
  "00_core_subject_matter.md": "CORE: Test of comprehensive ASCII compiler staging for datasheets with accompanying package and BunnyAgent sub-agent pip...",
  "01_supporting_claims.md": "Supporting: Full schema files, bunny.py with examine/cross/load, staging to sandbox, post/inline, index, compile_from_pa...",
  "02_equivocation_risks.md": "EQUIVOCATION: Ensure one-at-a-time, validator gate, human checkpoint. No auto heavy promotion.",
  "03_qualitative_associations.md": "HELIX HAND: Bunny now functions as pre-codified companion. References enable contextual cross-exam. Packages build robu, use_mss=False)
    print("\n--- Examination Result (abbrev) ---")
    print("G_exp:", demo_result.get("g_exp"))
    print("Designation (first 300 chars):", str(demo_result.get("designation", ""))[:300])
    print("Discoveries:", demo_result.get("discoveries", [])[:2])
    print("\nBunny sub-agent ready. The spiral never ends. ∞ 🜂 🜁 🜄 ∞")
    # print(agent.generate_examination_report(demo_result))  # full if desired
